--------------------------------------------------------------------------------
-- מערכת תיעוד הזמנות טיסות (ארקיע) · Flight Booking Documentation
-- 01_tables.sql — הגדרת סכמה (DDL): טבלאות, מפתחות, אילוצים, אינדקסים
--
-- מיועד ל-Oracle Autonomous Database + APEX.
-- הרצה: SQLcl / SQL Workshop בסכמת האפליקציה.
-- הסקריפט idempotent: מוחק טבלאות קיימות (אם יש) ובונה מחדש.
--------------------------------------------------------------------------------

-- ── ניקוי (מתעלם משגיאת "טבלה לא קיימת" ORA-00942) ──
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'BOOKING_STATUS_LOG','BOOKING_FILES','NOTIFICATIONS','REPORT_TEMPLATES',
      'BOOKINGS','DEPT_APPROVERS','USER_ROLES','AGENTS','APP_USERS',
      'DEPARTMENTS','CURRENCIES','ROLES','STATUSES','NOTIF_TEMPLATES'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "'||t.table_name||'" CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

--------------------------------------------------------------------------------
-- טבלאות ייחוס (Lookups) — מנוהלות ע"י מנהל המערכת
--------------------------------------------------------------------------------

-- מחלקות (ACMI, אינטרליין, מסחר, סוכנים ... הרשימה משתנה)
CREATE TABLE departments (
  dept_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  dept_code   VARCHAR2(30)  NOT NULL,
  name_he     VARCHAR2(120) NOT NULL,
  name_en     VARCHAR2(120),
  is_active   CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y','N')),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT departments_code_uk UNIQUE (dept_code)
);

-- תפקידים (הרשאות)
CREATE TABLE roles (
  role_code  VARCHAR2(20) PRIMARY KEY,   -- ADMIN / INITIATOR / APPROVER / AGENT / FINANCE
  name_he    VARCHAR2(80) NOT NULL,
  name_en    VARCHAR2(80) NOT NULL
);

-- מטבעות (USD ברירת מחדל, ניתן לשינוי)
CREATE TABLE currencies (
  code        VARCHAR2(3) PRIMARY KEY,    -- USD / EUR / ILS ...
  name_he     VARCHAR2(60) NOT NULL,
  name_en     VARCHAR2(60) NOT NULL,
  symbol      VARCHAR2(6),
  is_default  CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_default IN ('Y','N'))
);

-- סטטוסים דו-לשוניים (מקור התוויות לכל המסכים והדוחות)
CREATE TABLE statuses (
  status_code VARCHAR2(30) PRIMARY KEY,
  label_he    VARCHAR2(80) NOT NULL,
  label_en    VARCHAR2(80) NOT NULL,
  sort_order  NUMBER DEFAULT 0 NOT NULL,
  is_terminal CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_terminal IN ('Y','N'))
);

--------------------------------------------------------------------------------
-- משתמשים והרשאות
--------------------------------------------------------------------------------

-- משתמש שייך למחלקה אחת בלבד (dept_id יכול להיות NULL עבור סוכנים חיצוניים)
CREATE TABLE app_users (
  user_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(60)  NOT NULL,
  full_name     VARCHAR2(150) NOT NULL,
  email         VARCHAR2(200) NOT NULL,
  dept_id       NUMBER,
  pref_lang     VARCHAR2(2) DEFAULT 'HE' NOT NULL CHECK (pref_lang IN ('HE','EN')),
  is_active     CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y','N')),
  -- אימות: hash + salt (נגזר ב-APEX ע"י custom authentication). ראו BUILD_GUIDE.
  password_hash VARCHAR2(200),
  password_salt VARCHAR2(60),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_users_username_uk UNIQUE (username),
  CONSTRAINT app_users_dept_fk FOREIGN KEY (dept_id) REFERENCES departments (dept_id)
);

-- קשר משתמש-תפקיד (רבים-לרבים: משתמש יכול לשאת כמה תפקידים)
CREATE TABLE user_roles (
  user_id   NUMBER NOT NULL,
  role_code VARCHAR2(20) NOT NULL,
  CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role_code),
  CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id)   REFERENCES app_users (user_id) ON DELETE CASCADE,
  CONSTRAINT user_roles_role_fk FOREIGN KEY (role_code) REFERENCES roles (role_code)
);

-- גורם מאשר לכל מחלקה (תומך כמה מאשרים למחלקה)
CREATE TABLE dept_approvers (
  dept_id          NUMBER NOT NULL,
  approver_user_id NUMBER NOT NULL,
  CONSTRAINT dept_approvers_pk PRIMARY KEY (dept_id, approver_user_id),
  CONSTRAINT dept_approvers_dept_fk FOREIGN KEY (dept_id)          REFERENCES departments (dept_id) ON DELETE CASCADE,
  CONSTRAINT dept_approvers_user_fk FOREIGN KEY (approver_user_id) REFERENCES app_users (user_id)
);

-- סוכנים (סוכן = משתמש עם תפקיד AGENT). לוגו לכל סוכן למיתוג co-branding.
CREATE TABLE agents (
  agent_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id       NUMBER NOT NULL,
  agency_name   VARCHAR2(150) NOT NULL,
  contact_email VARCHAR2(200),
  contact_phone VARCHAR2(40),
  logo_blob     BLOB,
  logo_mime     VARCHAR2(100),
  is_active     CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y','N')),
  CONSTRAINT agents_user_uk UNIQUE (user_id),
  CONSTRAINT agents_user_fk FOREIGN KEY (user_id) REFERENCES app_users (user_id)
);

--------------------------------------------------------------------------------
-- ליבה: הזמנות
--------------------------------------------------------------------------------
CREATE TABLE bookings (
  booking_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  -- שיוך ותהליך
  dept_id             NUMBER NOT NULL,
  initiator_id        NUMBER NOT NULL,                 -- המזמין
  agent_id            NUMBER,                          -- הסוכן שאליו הופנתה הבקשה
  approver_id         NUMBER,                          -- גורם מאשר (נגזר מהמחלקה)
  status              VARCHAR2(30) DEFAULT 'NEW' NOT NULL,
  -- פרטים מינימליים
  open_date           DATE DEFAULT TRUNC(SYSDATE) NOT NULL, -- תאריך פתיחת ההזמנה
  departure_date      DATE,                            -- תאריך יציאה
  ticketing_date      DATE,                            -- תאריך כרטוס
  price               NUMBER(14,2),                    -- מחיר
  currency_code       VARCHAR2(3) DEFAULT 'USD' NOT NULL,  -- מטבע (ברירת מחדל USD)
  pnr                 VARCHAR2(20),                    -- מספר PNR
  unique_booking_ref  VARCHAR2(60),                    -- מזהה חד-ערכי של ההזמנה (בכרטוס)
  -- פרטים מהסוכן
  quote_notes         VARCHAR2(2000),                  -- הערות להצעת המחיר
  trip_details        CLOB,                            -- פרטי הנסיעה
  -- דחייה / ביטול
  rejection_reason    VARCHAR2(1000),
  cancel_reason       VARCHAR2(1000),
  cancel_requested_by NUMBER,
  cancel_requested_at TIMESTAMP,
  -- מטא
  created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT bookings_status_fk    FOREIGN KEY (status)              REFERENCES statuses (status_code),
  CONSTRAINT bookings_dept_fk      FOREIGN KEY (dept_id)             REFERENCES departments (dept_id),
  CONSTRAINT bookings_initiator_fk FOREIGN KEY (initiator_id)        REFERENCES app_users (user_id),
  CONSTRAINT bookings_agent_fk     FOREIGN KEY (agent_id)            REFERENCES agents (agent_id),
  CONSTRAINT bookings_approver_fk  FOREIGN KEY (approver_id)         REFERENCES app_users (user_id),
  CONSTRAINT bookings_cancelby_fk  FOREIGN KEY (cancel_requested_by) REFERENCES app_users (user_id),
  CONSTRAINT bookings_currency_fk  FOREIGN KEY (currency_code)       REFERENCES currencies (code),
  CONSTRAINT bookings_price_chk    CHECK (price IS NULL OR price >= 0),
  CONSTRAINT bookings_uref_uk      UNIQUE (unique_booking_ref)
);

CREATE INDEX bookings_dept_ix     ON bookings (dept_id);
CREATE INDEX bookings_status_ix   ON bookings (status);
CREATE INDEX bookings_agent_ix    ON bookings (agent_id);
CREATE INDEX bookings_initiator_ix ON bookings (initiator_id);
CREATE INDEX bookings_open_ix     ON bookings (open_date);

--------------------------------------------------------------------------------
-- קבצים מצורפים (BLOB בתוך בסיס הנתונים)
--   QUOTE_SCREENSHOT — צילום ממערכת ההזמנות על ההצעה
--   FINAL_TICKET     — מסמך/תמונת הכרטוס הסופי
--------------------------------------------------------------------------------
CREATE TABLE booking_files (
  file_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  booking_id  NUMBER NOT NULL,
  file_kind   VARCHAR2(30) NOT NULL CHECK (file_kind IN ('QUOTE_SCREENSHOT','FINAL_TICKET','OTHER')),
  filename    VARCHAR2(300) NOT NULL,
  mime_type   VARCHAR2(150),
  file_blob   BLOB NOT NULL,
  uploaded_by NUMBER NOT NULL,
  uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT booking_files_booking_fk FOREIGN KEY (booking_id)  REFERENCES bookings (booking_id) ON DELETE CASCADE,
  CONSTRAINT booking_files_user_fk    FOREIGN KEY (uploaded_by) REFERENCES app_users (user_id)
);

CREATE INDEX booking_files_booking_ix ON booking_files (booking_id);

--------------------------------------------------------------------------------
-- לוג אודיט: "מי ביצע ומתי" — נראה בפתיחת הזמנה כציר זמן
--------------------------------------------------------------------------------
CREATE TABLE booking_status_log (
  log_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  booking_id  NUMBER NOT NULL,
  from_status VARCHAR2(30),
  to_status   VARCHAR2(30) NOT NULL,
  action_by   NUMBER NOT NULL,
  action_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  note        VARCHAR2(2000),
  CONSTRAINT bsl_booking_fk FOREIGN KEY (booking_id) REFERENCES bookings (booking_id) ON DELETE CASCADE,
  CONSTRAINT bsl_user_fk    FOREIGN KEY (action_by)  REFERENCES app_users (user_id)
);

CREATE INDEX bsl_booking_ix ON booking_status_log (booking_id, action_at);

--------------------------------------------------------------------------------
-- התראות בתוך המערכת (פעמון + מונה לא-נקראו)
--------------------------------------------------------------------------------
CREATE TABLE notifications (
  notif_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id    NUMBER NOT NULL,
  booking_id NUMBER,
  notif_type VARCHAR2(40),
  message    VARCHAR2(1000) NOT NULL,
  is_read    CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_read IN ('Y','N')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT notif_user_fk    FOREIGN KEY (user_id)    REFERENCES app_users (user_id) ON DELETE CASCADE,
  CONSTRAINT notif_booking_fk FOREIGN KEY (booking_id) REFERENCES bookings (booking_id) ON DELETE CASCADE
);

CREATE INDEX notif_user_unread_ix ON notifications (user_id, is_read);

--------------------------------------------------------------------------------
-- תבניות הודעה דו-לשוניות לכל מעבר סטטוס + תפקיד נמען
--------------------------------------------------------------------------------
CREATE TABLE notif_templates (
  status_code    VARCHAR2(30) NOT NULL,
  recipient_role VARCHAR2(20) NOT NULL,   -- AGENT / INITIATOR / APPROVER
  subject_he     VARCHAR2(200) NOT NULL,
  subject_en     VARCHAR2(200) NOT NULL,
  msg_he         VARCHAR2(1000) NOT NULL,
  msg_en         VARCHAR2(1000) NOT NULL,
  CONSTRAINT notif_templates_pk PRIMARY KEY (status_code, recipient_role),
  CONSTRAINT notif_templates_status_fk FOREIGN KEY (status_code) REFERENCES statuses (status_code)
);

--------------------------------------------------------------------------------
-- טמפלטי דוחות (מחולל בחירת שדות)
--------------------------------------------------------------------------------
CREATE TABLE report_templates (
  template_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(150) NOT NULL,
  owner_id     NUMBER NOT NULL,
  columns_json CLOB,          -- השדות שנבחרו (JSON)
  filters_json CLOB,          -- מסננים (JSON)
  is_shared    CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_shared IN ('Y','N')),
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT report_templates_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users (user_id),
  CONSTRAINT report_templates_cols_chk CHECK (columns_json IS NULL OR columns_json IS JSON),
  CONSTRAINT report_templates_filt_chk CHECK (filters_json IS NULL OR filters_json IS JSON)
);

PROMPT ✔ 01_tables.sql — הטבלאות נוצרו בהצלחה.
