--------------------------------------------------------------------------------
-- prod_reset.sql — איפוס נתוני הזמנות לקראת עלייה לפרודקשן
--------------------------------------------------------------------------------
-- מוחק את כל נתוני ההזמנות (הזמנות, קבצים, לוג סטטוסים, התראות, טוקני-פעולה)
-- ומשאיר על כנם: משתמשים, תפקידים, מחלקות, מאשרי-מחלקה, סוכנים, מפעילים רטובים,
-- שדות תעופה, מטבעות, סטטוסים ותבניות דוחות.
--
-- ⚠ פעולה חד-פעמית והרסנית — מריצים ידנית פעם אחת, לא חלק מהדיפלוי האוטומטי.
-- הרצה: SQLcl / SQL Workshop, מחוברים כסכמת ARKIA.
--     @bookings/deploy/prod_reset.sql
--------------------------------------------------------------------------------
set serveroutput on
set define off

-- ── לפני: כמה רשומות קיימות ──
DECLARE
  n_book NUMBER; n_file NUMBER; n_log NUMBER; n_notif NUMBER; n_tok NUMBER; n_user NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_book  FROM bookings;
  SELECT COUNT(*) INTO n_file  FROM booking_files;
  SELECT COUNT(*) INTO n_log   FROM booking_status_log;
  SELECT COUNT(*) INTO n_notif FROM notifications;
  BEGIN SELECT COUNT(*) INTO n_tok FROM booking_action_tokens; EXCEPTION WHEN OTHERS THEN n_tok := 0; END;
  SELECT COUNT(*) INTO n_user  FROM app_users;
  DBMS_OUTPUT.PUT_LINE('=== לפני האיפוס ===');
  DBMS_OUTPUT.PUT_LINE('  הזמנות='||n_book||'  קבצים='||n_file||'  לוג='||n_log||
                       '  התראות='||n_notif||'  טוקנים='||n_tok||'  משתמשים(יישמרו)='||n_user);
END;
/

-- ── מחיקה ── (booking_files / booking_status_log / notifications נמחקים ב-CASCADE עם bookings)
BEGIN
  -- טוקני פעולה (ללא FK-Cascade) — מחיקה מפורשת
  BEGIN EXECUTE IMMEDIATE 'DELETE FROM booking_action_tokens'; EXCEPTION WHEN OTHERS THEN NULL; END;
  -- התראות (למקרה של רשומות עם booking_id NULL שלא ייתפסו ב-CASCADE)
  DELETE FROM notifications;
  -- ההזמנות עצמן — גורר CASCADE ל-booking_files / booking_status_log / notifications
  DELETE FROM bookings;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('=== נמחקו כל נתוני ההזמנות ===');
END;
/

-- ── איפוס מונה מזהה ההזמנות כך שההזמנה הראשונה בפרוד תהיה #1 ──
-- (אם אינכם רוצים לאפס את המונה — מחקו/העירו את הבלוק הזה)
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings MODIFY booking_id GENERATED BY DEFAULT ON NULL AS IDENTITY (RESTART START WITH 1)';
  DBMS_OUTPUT.PUT_LINE('מונה מזהה ההזמנות אופס ל-1.');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('לא ניתן לאפס את המונה (לא קריטי): '||SQLERRM);
END;
/

-- ── אחרי: אימות ──
DECLARE
  n_book NUMBER; n_user NUMBER; n_dept NUMBER; n_air NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_book FROM bookings;
  SELECT COUNT(*) INTO n_user FROM app_users;
  SELECT COUNT(*) INTO n_dept FROM departments;
  SELECT COUNT(*) INTO n_air  FROM airports;
  DBMS_OUTPUT.PUT_LINE('=== אחרי האיפוס ===');
  DBMS_OUTPUT.PUT_LINE('  הזמנות='||n_book||' (אמור להיות 0)');
  DBMS_OUTPUT.PUT_LINE('  משתמשים='||n_user||'  מחלקות='||n_dept||'  שדות תעופה='||n_air||' (נשמרו)');
END;
/

PROMPT ✔ prod_reset.sql — נתוני ההזמנות נמחקו, המשתמשים והנתונים הקבועים נשמרו.
