--------------------------------------------------------------------------------
-- מערכת תיעוד הזמנות טיסות (ארקיע) · install_api.sql
-- שכבת REST (ORDS) מעל סכמת ARKIA — מאפשרת לאפליקציית ה-HTML לעבוד רב-משתמשי
-- על אותה אורקל, בלי לבנות עמודים ב-APEX.
--
-- להרצה בסכמת ARKIA (Database Actions → SQL, מחוברים כ-ARKIA), F5 / Run Script.
-- דורש: 01-04 (install_all.sql) הותקנו כבר; הסכמה ARKIA מופעלת ל-ORDS.
--
-- Base path: /ords/arkia/api/...
-- אימות: POST api/login → token; שאר הקריאות מוסרות token (query/body).
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- מיגרציית סכמה (idempotent) — נוספת אוטומטית בכל פריסת CI.
-- הערה: bookings/db/** אינו נפרס אוטומטית, ולכן שינויי הסכמה הנדרשים לשיפורים
--       (שדות חדשים בהזמנה, טבלאות מפעיל-רטוב ושדות-תעופה) מבוצעים כאן, בבטחה,
--       בלי למחוק נתונים קיימים.
--------------------------------------------------------------------------------
DECLARE
  PROCEDURE try (p_ddl VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_ddl;
  EXCEPTION WHEN OTHERS THEN NULL;  -- עמודה/טבלה כבר קיימת → התעלם (idempotent)
  END;
BEGIN
  -- שדות חדשים בהזמנה
  try('ALTER TABLE bookings ADD (pax_count NUMBER DEFAULT 1)');
  try('ALTER TABLE bookings ADD (pref_time VARCHAR2(20))');
  try('ALTER TABLE bookings ADD (wet_operator_id NUMBER)');
  try('ALTER TABLE bookings ADD (origin_iata VARCHAR2(4))');
  try('ALTER TABLE bookings ADD (dest_iata VARCHAR2(4))');
  try('ALTER TABLE bookings ADD (low_cost CHAR(1) DEFAULT ''N'')');   -- טיסת LOW COST (הסוכן מסמן בהצעה)
  try('ALTER TABLE bookings ADD (urgent CHAR(1) DEFAULT ''N'')');     -- הצעה דחופה יזומה ע"י הסוכן
  -- העדפת התראות מייל לכל משתמש (Y=מקבל, N=כבוי)
  try('ALTER TABLE app_users ADD (notify_email CHAR(1) DEFAULT ''Y'')');
  -- לוג כניסות למערכת (התחברויות בלבד — לא פעולות)
  try('CREATE TABLE login_log (
        log_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        user_id  NUMBER,
        username VARCHAR2(60),
        login_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  -- טוקני פעולה חד-פעמיים (למשל אישור הצעה מתוך המייל, ללא כניסה למערכת)
  try('CREATE TABLE booking_action_tokens (
        token      VARCHAR2(70) PRIMARY KEY,
        booking_id NUMBER NOT NULL,
        action     VARCHAR2(20) NOT NULL,
        user_id    NUMBER,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        expires_at TIMESTAMP,
        used       CHAR(1) DEFAULT ''N'' NOT NULL)');
  -- טבלת מפעיל רטוב (ACMI) — מנוהלת ע"י אדמין
  try('CREATE TABLE wet_operators (
        operator_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name_he     VARCHAR2(80) NOT NULL,
        name_en     VARCHAR2(80),
        is_active   CHAR(1) DEFAULT ''Y'' NOT NULL)');
  -- טבלת שדות תעופה (נתיב טיסה לפי IATA) — מנוהלת ע"י אדמין
  try('CREATE TABLE airports (
        iata      VARCHAR2(4) PRIMARY KEY,
        name_he   VARCHAR2(120),
        name_en   VARCHAR2(120),
        city_he   VARCHAR2(80),
        city_en   VARCHAR2(80),
        country   VARCHAR2(60),
        is_active CHAR(1) DEFAULT ''Y'' NOT NULL)');
  -- הרחבת עמודות שדות התעופה (שמות אנגליים ארוכים ממערכת התמחיר)
  try('ALTER TABLE airports MODIFY (name_he VARCHAR2(200))');
  try('ALTER TABLE airports MODIFY (name_en VARCHAR2(200))');
  try('ALTER TABLE airports MODIFY (city_he VARCHAR2(200))');
  try('ALTER TABLE airports MODIFY (city_en VARCHAR2(200))');
  try('ALTER TABLE airports MODIFY (country VARCHAR2(100))');
END;
/

-- ── זריעת מפעילי רטוב (idempotent לפי שם) ──
DECLARE
  PROCEDURE seed_op (p_he VARCHAR2, p_en VARCHAR2) IS
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM wet_operators WHERE name_he = p_he;
    IF n = 0 THEN INSERT INTO wet_operators (name_he, name_en) VALUES (p_he, p_en); END IF;
  END;
BEGIN
  seed_op('פליי-לילי', 'Flylili');
  seed_op('הייפליי',   'HiFly');
  seed_op('גוליבר',    'Gulliver');
  seed_op('אלקטרה',    'Electra');
  seed_op('נאוס',      'Neos');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ── זריעת שדות תעופה (idempotent, MERGE לפי IATA) ──
DECLARE
  PROCEDURE seed_ap (p_iata VARCHAR2, p_he VARCHAR2, p_en VARCHAR2, p_country VARCHAR2) IS
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM airports WHERE iata = p_iata;
    IF n = 0 THEN
      INSERT INTO airports (iata, name_he, name_en, city_he, city_en, country)
      VALUES (p_iata, p_he, p_en, p_he, p_en, p_country);
    END IF;
  EXCEPTION WHEN OTHERS THEN NULL;  -- כשל בשורה בודדת לא יפיל את כל הקבוצה
  END;
BEGIN
  seed_ap('TLV','תל אביב (בן גוריון)','Tel Aviv (Ben Gurion)','ישראל');
  seed_ap('ETM','אילת (רמון)','Eilat (Ramon)','ישראל');
  seed_ap('ETH','אילת (העיר)','Eilat City','ישראל');
  seed_ap('VDA','עובדה','Ovda','ישראל');
  seed_ap('AMS','אמסטרדם','Amsterdam','הולנד');
  seed_ap('ATH','אתונה','Athens','יוון');
  seed_ap('BCN','ברצלונה','Barcelona','ספרד');
  seed_ap('MAD','מדריד','Madrid','ספרד');
  seed_ap('BER','ברלין','Berlin','גרמניה');
  seed_ap('MUC','מינכן','Munich','גרמניה');
  seed_ap('FRA','פרנקפורט','Frankfurt','גרמניה');
  seed_ap('BUD','בודפשט','Budapest','הונגריה');
  seed_ap('PRG','פראג','Prague','צ׳כיה');
  seed_ap('VIE','וינה','Vienna','אוסטריה');
  seed_ap('ZRH','ציריך','Zurich','שווייץ');
  seed_ap('GVA','ז׳נבה','Geneva','שווייץ');
  seed_ap('CDG','פריז (שארל דה גול)','Paris (CDG)','צרפת');
  seed_ap('ORY','פריז (אורלי)','Paris (Orly)','צרפת');
  seed_ap('NCE','ניס','Nice','צרפת');
  seed_ap('FCO','רומא (פיומיצ׳ינו)','Rome (FCO)','איטליה');
  seed_ap('MXP','מילאנו (מלפנסה)','Milan (MXP)','איטליה');
  seed_ap('VCE','ונציה','Venice','איטליה');
  seed_ap('NAP','נאפולי','Naples','איטליה');
  seed_ap('LCA','לרנקה','Larnaca','קפריסין');
  seed_ap('PFO','פאפוס','Paphos','קפריסין');
  seed_ap('RHO','רודוס','Rhodes','יוון');
  seed_ap('HER','הרקליון (כרתים)','Heraklion','יוון');
  seed_ap('JTR','סנטוריני','Santorini','יוון');
  seed_ap('JMK','מיקונוס','Mykonos','יוון');
  seed_ap('CFU','קורפו','Corfu','יוון');
  seed_ap('SKG','סלוניקי','Thessaloniki','יוון');
  seed_ap('TBS','טביליסי','Tbilisi','גאורגיה');
  seed_ap('KUT','קוטאיסי','Kutaisi','גאורגיה');
  seed_ap('BUS','בטומי','Batumi','גאורגיה');
  seed_ap('SOF','סופיה','Sofia','בולגריה');
  seed_ap('OTP','בוקרשט','Bucharest','רומניה');
  seed_ap('LHR','לונדון (הית׳רו)','London (Heathrow)','בריטניה');
  seed_ap('LTN','לונדון (לוטון)','London (Luton)','בריטניה');
  seed_ap('RAK','מרקש','Marrakesh','מרוקו');
  seed_ap('DXB','דובאי','Dubai','איחוד האמירויות');
  seed_ap('JFK','ניו יורק (JFK)','New York (JFK)','ארה״ב');
  seed_ap('EWR','ניוארק','Newark','ארה״ב');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ── יעדים ממערכת התמחיר (idempotent, MERGE לפי IATA) ──
DECLARE
  PROCEDURE seed_ap (p_iata VARCHAR2, p_he VARCHAR2, p_en VARCHAR2, p_country VARCHAR2) IS
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM airports WHERE iata = p_iata;
    IF n = 0 THEN
      INSERT INTO airports (iata, name_he, name_en, city_he, city_en, country)
      VALUES (p_iata, p_he, p_en, p_he, p_en, p_country);
    END IF;
  EXCEPTION WHEN OTHERS THEN NULL;  -- כשל בשורה בודדת לא יפיל את כל הקבוצה
  END;
BEGIN
  seed_ap('AUH','אבו דאבי','Zayed International Airport','איחוד האמירויות הערביות');
  seed_ap('ADD','אדיס אבבה','Addis Ababa Bole International Airport','אתיופיה');
  seed_ap('AGA','אגאדיר','Agadir–Al Massira Airport','מרוקו');
  seed_ap('ALA','אלמטי','Almaty International Airport','קזחסטן');
  seed_ap('AMM','עמאן','Queen Alia International Airport','ירדן');
  seed_ap('AYT','אנטליה','Antalya Airport','טורקיה');
  seed_ap('AMS','אמסטרדם','Amsterdam Schiphol Airport','הולנד');
  seed_ap('PVK','פרבזה','Aktion National Airport','יוון');
  seed_ap('ATH','אתונה','Athens International Airport (Eleftherios Venizelos)','יוון');
  seed_ap('BCM','בקאו','Bacau International Airport','רומניה');
  seed_ap('BAH','בחריין','Bahrain International Airport','בחריין');
  seed_ap('GYD','באקו','Heydar Aliyev International Airport','אזרביג׳אן');
  seed_ap('BUS','בתומי','Batumi International Airport','גאורגיה');
  seed_ap('BCN','ברצלונה','Josep Tarradellas Airport Barcelona-El Prat','ספרד');
  seed_ap('BEG','בלגרד','Belgrade Nikola Tesla Airport','סרביה');
  seed_ap('BLR','בנגלור','Kempegowda International Airport','הודו');
  seed_ap('BER','ברלין','Berlin Brandenburg Airport','גרמניה');
  seed_ap('BGO','ברגן','Bergen Airport','נורווגיה');
  seed_ap('BGY','ברגמו','Bergamo-Il Caravaggio','איטליה');
  seed_ap('GBE','גאבורונה','Sir Seretse Khama International Airport','בוטסואנה');
  seed_ap('KBP','קייב','Boryspil International Airport','אוקראינה');
  seed_ap('BLQ','בולוניה','Bologna Guglielmo Marconi Airport','איטליה');
  seed_ap('BTS','ברטיסלאבה','M. R. Stefanik Airport','סלובקיה');
  seed_ap('BRU','בריסל','Brussels Airport','בלגיה');
  seed_ap('BUD','בודפשט','Budapest Ferenc Liszt International Airport','הונגריה');
  seed_ap('BOJ','בורגס','Burgas Airport','בולגריה');
  seed_ap('SJJ','סרייבו','Sarajevo International Airport','בוסניה והרצגובינה');
  seed_ap('OTP','בוקרשט','Henri Coanda International Airport','רומניה');
  seed_ap('CMN','קזבלנקה','Mohammed V International Airport','מרוקו');
  seed_ap('CAG','קליארי','Cagliari Elmas Airport','איטליה');
  seed_ap('CTA','קטניה','Catania-Fontanarossa Airport','איטליה');
  seed_ap('KIV','קישינב','Chisinau International Airport','מולדובה');
  seed_ap('CPH','קופנהגן','Copenhagen Airport','דנמרק');
  seed_ap('CFU','קורפו','Corfu International Airport','יוון');
  seed_ap('DSS','דקאר','Blaise Diagne International Airport','סנגל');
  seed_ap('JIB','ג׳יבוטי','Djibouti-Ambouli International Airport','ג׳יבוטי');
  seed_ap('DBV','דוברובניק','Dubrovnik Airport','קרואטיה');
  seed_ap('DEB','דברצן','Debrecen International Airport','הונגריה');
  seed_ap('DXB','דובאי','Dubai International Airport','איחוד האמירויות הערביות');
  seed_ap('EIN','איינדהובן','Eindhoven Airport','הולנד');
  seed_ap('EDI','אדינבורו','Edinburgh Airport','הממלכה המאוחדת');
  seed_ap('FRA','פרנקפורט','Frankfurt Airport','גרמניה');
  seed_ap('GPA','פטרס','Araxos Airport','יוון');
  seed_ap('GLA','גלאזגו','Glasgow Airport','הממלכה המאוחדת');
  seed_ap('GOI','גואה','Dabolim Airport','הודו');
  seed_ap('GOX','גואה','Mopa Airport','הודו');
  seed_ap('GNB','גרנובל','Grenoble-Isere Airport','צרפת');
  seed_ap('GDN','גדנסק','Gdansk Lech Walesa Airport','פולין');
  seed_ap('GVA','ז׳נבה','Geneva International Airport','שווייץ');
  seed_ap('LPA','לאס פאלמס','Gran Canaria Airport','ספרד');
  seed_ap('LCJ','לודז׳','Lodz Wladyslaw Reymont Airport','פולין');
  seed_ap('HEL','הלסינקי','Helsinki Airport','פינלנד');
  seed_ap('HER','הרקליון','Heraklion International Airport (Nikos Kazantzakis)','יוון');
  seed_ap('HRG','הורגדה','Hurghada International Airport','מצרים');
  seed_ap('LHR','לונדון','London Heathrow Airport','הממלכה המאוחדת');
  seed_ap('LTN','לונדון','London Luton Airport','הממלכה המאוחדת');
  seed_ap('IST','איסטנבול','Istanbul Airport','טורקיה');
  seed_ap('IBZ','איביזה','Ibiza Airport','ספרד');
  seed_ap('NOS','מחוז אנצינאנה','Fascene Airport','מדגסקר');
  seed_ap('RMI','רימיני','Federico Fellini International Airport','איטליה');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/



-- ── טבלת סשנים (טוקנים) ── נוצרת רק אם אינה קיימת, כדי שסשנים ישרדו פריסות
-- (משתמשים נשארים מחוברים במובייל בין דeployments).
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'API_SESSIONS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE api_sessions (
      token      VARCHAR2(64) PRIMARY KEY,
      user_id    NUMBER NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      expires_at TIMESTAMP DEFAULT SYSTIMESTAMP + INTERVAL ''30'' DAY NOT NULL,
      CONSTRAINT api_sessions_user_fk FOREIGN KEY (user_id) REFERENCES app_users (user_id) ON DELETE CASCADE)';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- חבילת ה-API — בונה JSON ומריצה את זרימת booking_pkg
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE api_pkg AS
  PROCEDURE emit (p_json CLOB);
  PROCEDURE emit_preflight;
  FUNCTION  err (p_msg VARCHAR2) RETURN CLOB;
  FUNCTION  uid (p_token VARCHAR2) RETURN NUMBER;
  FUNCTION  has_role (p_uid NUMBER, p_role VARCHAR2) RETURN VARCHAR2;

  FUNCTION  login        (p_username VARCHAR2, p_password VARCHAR2) RETURN CLOB;
  FUNCTION  bootstrap    (p_token VARCHAR2) RETURN CLOB;
  FUNCTION  list_bookings(p_token VARCHAR2) RETURN CLOB;
  FUNCTION  get_booking  (p_token VARCHAR2, p_id NUMBER) RETURN CLOB;
  FUNCTION  create_booking(p_token VARCHAR2, p_departure VARCHAR2, p_notes VARCHAR2,
                           p_pax NUMBER, p_pref_time VARCHAR2, p_wet_op NUMBER,
                           p_origin VARCHAR2, p_dest VARCHAR2) RETURN CLOB;
  FUNCTION  edit_booking (p_token VARCHAR2, p_id NUMBER, p_departure VARCHAR2, p_agent_id NUMBER,
                          p_notes VARCHAR2, p_pax NUMBER, p_pref_time VARCHAR2, p_wet_op NUMBER,
                          p_origin VARCHAR2, p_dest VARCHAR2) RETURN CLOB;
  FUNCTION  do_action    (p_token VARCHAR2, p_id NUMBER, p_action VARCHAR2,
                          p_price NUMBER, p_currency VARCHAR2, p_trip CLOB, p_notes VARCHAR2,
                          p_pnr VARCHAR2, p_ref VARCHAR2, p_tdate VARCHAR2, p_reason VARCHAR2,
                          p_low_cost VARCHAR2 DEFAULT NULL) RETURN CLOB;
  FUNCTION  agent_create_quote (p_token VARCHAR2, p_dept_id NUMBER, p_departure VARCHAR2, p_pax NUMBER,
                          p_pref_time VARCHAR2, p_origin VARCHAR2, p_dest VARCHAR2, p_price NUMBER,
                          p_currency VARCHAR2, p_trip CLOB, p_notes VARCHAR2, p_low_cost VARCHAR2) RETURN CLOB;
  FUNCTION  add_file     (p_token VARCHAR2, p_booking_id NUMBER, p_kind VARCHAR2,
                          p_filename VARCHAR2, p_mime VARCHAR2, p_data CLOB) RETURN CLOB;
  PROCEDURE get_file     (p_id NUMBER, o_blob OUT BLOB, o_mime OUT VARCHAR2, o_name OUT VARCHAR2);
  FUNCTION  notifications(p_token VARCHAR2) RETURN CLOB;
  FUNCTION  mark_read    (p_token VARCHAR2) RETURN CLOB;
  -- ── ניהול (ADMIN בלבד) ──
  FUNCTION  admin_users  (p_token VARCHAR2) RETURN CLOB;
  FUNCTION  admin_create_dept (p_token VARCHAR2, p_code VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2) RETURN CLOB;
  FUNCTION  admin_update_dept (p_token VARCHAR2, p_dept_id NUMBER, p_code VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2) RETURN CLOB;
  FUNCTION  admin_create_user (p_token VARCHAR2, p_username VARCHAR2, p_full VARCHAR2, p_email VARCHAR2,
                               p_dept_id NUMBER, p_role VARCHAR2, p_password VARCHAR2) RETURN CLOB;
  FUNCTION  admin_update_user (p_token VARCHAR2, p_user_id NUMBER, p_full VARCHAR2, p_email VARCHAR2,
                               p_dept_id NUMBER, p_is_active VARCHAR2) RETURN CLOB;
  FUNCTION  admin_setpw  (p_token VARCHAR2, p_username VARCHAR2, p_password VARCHAR2) RETURN CLOB;
  FUNCTION  admin_reset_pw (p_token VARCHAR2, p_user_id NUMBER) RETURN CLOB;
  FUNCTION  admin_create_wetop (p_token VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2) RETURN CLOB;
  FUNCTION  admin_airports (p_token VARCHAR2) RETURN CLOB;
  FUNCTION  admin_save_airport (p_token VARCHAR2, p_iata VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2,
                                p_country VARCHAR2, p_is_active VARCHAR2) RETURN CLOB;
  FUNCTION  admin_delete_user (p_token VARCHAR2, p_user_id NUMBER) RETURN CLOB;
  FUNCTION  admin_logins  (p_token VARCHAR2) RETURN CLOB;
  FUNCTION  set_notify    (p_token VARCHAR2, p_on VARCHAR2) RETURN CLOB;
  -- אישור/פעולה מתוך המייל (טוקן חד-פעמי) — מחזיר עמוד HTML
  FUNCTION  act_token     (p_t VARCHAR2) RETURN BLOB;
  -- מאשר לכל מחלקה
  FUNCTION  admin_dept_approvers (p_token VARCHAR2) RETURN CLOB;
  FUNCTION  admin_set_dept_approver (p_token VARCHAR2, p_dept_id NUMBER, p_user_id NUMBER) RETURN CLOB;
  FUNCTION  admin_del_dept_approver (p_token VARCHAR2, p_dept_id NUMBER, p_user_id NUMBER) RETURN CLOB;
  FUNCTION  admin_usage (p_token VARCHAR2) RETURN CLOB;
END api_pkg;
/

CREATE OR REPLACE PACKAGE BODY api_pkg AS

  PROCEDURE emit (p_json CLOB) IS
    l_len PLS_INTEGER := DBMS_LOB.getlength(p_json);
    l_off PLS_INTEGER := 1;
  BEGIN
    owa_util.mime_header('application/json', FALSE);
    htp.p('Access-Control-Allow-Origin: *');
    htp.p('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    htp.p('Access-Control-Allow-Headers: Content-Type, Authorization');
    owa_util.http_header_close;
    WHILE l_off <= l_len LOOP
      htp.prn(DBMS_LOB.substr(p_json, 6000, l_off));
      l_off := l_off + 6000;
    END LOOP;
  END emit;

  PROCEDURE emit_preflight IS
  BEGIN
    owa_util.mime_header('text/plain', TRUE);
  END emit_preflight;

  FUNCTION err (p_msg VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN '{"ok":false,"error":"'||REPLACE(REPLACE(NVL(p_msg,'error'),'\','\\'),'"','\"')||'"}';
  END err;

  FUNCTION uid (p_token VARCHAR2) RETURN NUMBER IS
    l NUMBER;
  BEGIN
    SELECT user_id INTO l FROM api_sessions WHERE token = p_token AND expires_at > SYSTIMESTAMP;
    RETURN l;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20401, 'invalid_or_expired_token');
  END uid;

  FUNCTION has_role (p_uid NUMBER, p_role VARCHAR2) RETURN VARCHAR2 IS
    n PLS_INTEGER;
  BEGIN
    SELECT COUNT(*) INTO n FROM user_roles WHERE user_id = p_uid AND role_code = p_role;
    RETURN CASE WHEN n > 0 THEN 'Y' ELSE 'N' END;
  END has_role;

  -- האם המשתמש רשאי לאשר/לדחות הזמנה: אדמין, המאשר המשויך, או מאשר מוגדר של מחלקת ההזמנה
  FUNCTION is_booking_approver (p_uid NUMBER, p_id NUMBER) RETURN BOOLEAN IS
    l_dept NUMBER; l_apr NUMBER; n PLS_INTEGER;
  BEGIN
    IF has_role(p_uid,'ADMIN') = 'Y' THEN RETURN TRUE; END IF;
    SELECT dept_id, approver_id INTO l_dept, l_apr FROM bookings WHERE booking_id = p_id;
    IF l_apr = p_uid THEN RETURN TRUE; END IF;
    SELECT COUNT(*) INTO n FROM dept_approvers WHERE dept_id = l_dept AND approver_user_id = p_uid;
    RETURN n > 0;
  EXCEPTION WHEN OTHERS THEN RETURN FALSE;
  END is_booking_approver;

  FUNCTION login (p_username VARCHAR2, p_password VARCHAR2) RETURN CLOB IS
    l_uid NUMBER; l_token VARCHAR2(64); l_dept NUMBER; l_lang VARCHAR2(2); l_full VARCHAR2(150); l_agent NUMBER;
    l_notify VARCHAR2(1);
  BEGIN
    IF NOT booking_pkg.authenticate(p_username, p_password) THEN RETURN err('bad_credentials'); END IF;
    SELECT user_id, dept_id, pref_lang, full_name, NVL(notify_email,'Y')
      INTO l_uid, l_dept, l_lang, l_full, l_notify
      FROM app_users WHERE LOWER(username) = LOWER(p_username);
    l_token := RAWTOHEX(SYS_GUID());
    INSERT INTO api_sessions (token, user_id, expires_at)
      VALUES (l_token, l_uid, SYSTIMESTAMP + INTERVAL '30' DAY);
    INSERT INTO login_log (user_id, username) VALUES (l_uid, LOWER(p_username));
    COMMIT;
    SELECT MAX(agent_id) INTO l_agent FROM agents WHERE user_id = l_uid;
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object;
      APEX_JSON.write('ok', TRUE);
      APEX_JSON.write('token', l_token);
      APEX_JSON.open_object('user');
        APEX_JSON.write('id', l_uid); APEX_JSON.write('username', LOWER(p_username));
        APEX_JSON.write('full_name', l_full); APEX_JSON.write('dept_id', l_dept); APEX_JSON.write('pref_lang', l_lang);
        APEX_JSON.write('notify_email', l_notify);
      APEX_JSON.close_object;
      APEX_JSON.open_array('roles');
        FOR r IN (SELECT role_code FROM user_roles WHERE user_id = l_uid) LOOP APEX_JSON.write(r.role_code); END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.write('agent_id', l_agent);
    APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END login;

  FUNCTION bootstrap (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token);
  BEGIN
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE);
      APEX_JSON.open_array('departments');
        FOR d IN (SELECT dept_id,dept_code,name_he,name_en FROM departments WHERE is_active='Y' ORDER BY dept_id) LOOP
          APEX_JSON.open_object; APEX_JSON.write('id',d.dept_id); APEX_JSON.write('code',d.dept_code);
          APEX_JSON.write('name_he',d.name_he); APEX_JSON.write('name_en',d.name_en); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.open_array('agents');
        FOR a IN (SELECT agent_id,agency_name FROM agents WHERE is_active='Y' ORDER BY agent_id) LOOP
          APEX_JSON.open_object; APEX_JSON.write('id',a.agent_id); APEX_JSON.write('name',a.agency_name); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.open_array('currencies');
        FOR c IN (SELECT code,symbol,is_default FROM currencies ORDER BY DECODE(is_default,'Y',0,1),code) LOOP
          APEX_JSON.open_object; APEX_JSON.write('code',c.code); APEX_JSON.write('symbol',c.symbol);
          APEX_JSON.write('is_default',c.is_default); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.open_array('statuses');
        FOR s IN (SELECT status_code,label_he,label_en,is_terminal FROM statuses ORDER BY sort_order) LOOP
          APEX_JSON.open_object; APEX_JSON.write('code',s.status_code); APEX_JSON.write('he',s.label_he);
          APEX_JSON.write('en',s.label_en); APEX_JSON.write('terminal',s.is_terminal); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.open_array('wet_operators');
        FOR w IN (SELECT operator_id,name_he,name_en FROM wet_operators WHERE is_active='Y' ORDER BY name_he) LOOP
          APEX_JSON.open_object; APEX_JSON.write('id',w.operator_id); APEX_JSON.write('name_he',w.name_he);
          APEX_JSON.write('name_en',NVL(w.name_en,w.name_he)); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.open_array('airports');
        FOR ap IN (SELECT iata,name_he,name_en,country FROM airports WHERE is_active='Y' ORDER BY iata) LOOP
          APEX_JSON.open_object; APEX_JSON.write('iata',ap.iata); APEX_JSON.write('name_he',ap.name_he);
          APEX_JSON.write('name_en',NVL(ap.name_en,ap.name_he)); APEX_JSON.write('country',ap.country); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
    APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END bootstrap;

  FUNCTION list_bookings (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token); l_all VARCHAR2(1); l_agent NUMBER; l_dept NUMBER;
  BEGIN
    l_all := CASE WHEN has_role(l_uid,'ADMIN')='Y' OR has_role(l_uid,'FINANCE')='Y' THEN 'Y' ELSE 'N' END;
    SELECT MAX(agent_id) INTO l_agent FROM agents WHERE user_id = l_uid;
    SELECT dept_id INTO l_dept FROM app_users WHERE user_id = l_uid;
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE); APEX_JSON.open_array('bookings');
    FOR b IN (
      SELECT b.booking_id, b.status, b.dept_id, d.name_he dhe, d.name_en den, ini.full_name ininame,
             b.agent_id, ag.agency_name agn, TO_CHAR(b.departure_date,'YYYY-MM-DD') dep,
             TO_CHAR(b.open_date,'YYYY-MM-DD') opn, TO_CHAR(b.ticketing_date,'YYYY-MM-DD') tkt,
             b.price, b.currency_code cur, b.pnr, b.pax_count pax, b.pref_time prt,
             b.origin_iata org, b.dest_iata dst, b.low_cost lowc, b.urgent urg, wo.name_he wohe, wo.name_en woen,
             (SELECT u2.full_name FROM booking_status_log l2 JOIN app_users u2 ON u2.user_id=l2.action_by
               WHERE l2.booking_id=b.booking_id ORDER BY l2.action_at DESC FETCH FIRST 1 ROW ONLY) lub,
             TO_CHAR((SELECT MAX(l3.action_at) FROM booking_status_log l3 WHERE l3.booking_id=b.booking_id),'YYYY-MM-DD HH24:MI') luat
      FROM bookings b JOIN departments d ON d.dept_id=b.dept_id
           JOIN app_users ini ON ini.user_id=b.initiator_id
           LEFT JOIN agents ag ON ag.agent_id=b.agent_id
           LEFT JOIN wet_operators wo ON wo.operator_id=b.wet_operator_id
      WHERE l_all='Y'
         OR (l_agent IS NOT NULL AND (b.agent_id=l_agent OR (b.agent_id IS NULL AND b.status='AWAITING_QUOTE')))
         OR (l_agent IS NULL AND b.dept_id=l_dept)
      ORDER BY b.booking_id DESC) LOOP
      APEX_JSON.open_object;
        APEX_JSON.write('id',b.booking_id); APEX_JSON.write('seq',b.booking_id); APEX_JSON.write('status',b.status);
        APEX_JSON.write('dept_id',b.dept_id); APEX_JSON.write('dept_he',b.dhe); APEX_JSON.write('dept_en',b.den);
        APEX_JSON.write('initiator',b.ininame); APEX_JSON.write('agent_id',b.agent_id); APEX_JSON.write('agent',b.agn);
        APEX_JSON.write('departure_date',b.dep); APEX_JSON.write('open_date',b.opn); APEX_JSON.write('ticketing_date',b.tkt);
        APEX_JSON.write('price',b.price); APEX_JSON.write('currency',b.cur); APEX_JSON.write('pnr',b.pnr);
        APEX_JSON.write('pax',b.pax); APEX_JSON.write('pref_time',b.prt);
        APEX_JSON.write('origin',b.org); APEX_JSON.write('dest',b.dst);
        APEX_JSON.write('wet_op_he',b.wohe); APEX_JSON.write('wet_op_en',NVL(b.woen,b.wohe));
        APEX_JSON.write('low_cost',b.lowc); APEX_JSON.write('urgent',b.urg);
        APEX_JSON.write('updated_by',b.lub); APEX_JSON.write('updated_at',b.luat);
      APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array; APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END list_bookings;

  FUNCTION get_booking (p_token VARCHAR2, p_id NUMBER) RETURN CLOB IS
    l_uid NUMBER := uid(p_token); r bookings%ROWTYPE;
    l_dhe VARCHAR2(120); l_den VARCHAR2(120); l_ini VARCHAR2(150); l_agn VARCHAR2(150); l_apr VARCHAR2(150);
    l_wohe VARCHAR2(80); l_woen VARCHAR2(80); l_dcode VARCHAR2(30);
  BEGIN
    SELECT * INTO r FROM bookings WHERE booking_id = p_id;
    SELECT name_he,name_en,dept_code INTO l_dhe,l_den,l_dcode FROM departments WHERE dept_id=r.dept_id;
    SELECT full_name INTO l_ini FROM app_users WHERE user_id=r.initiator_id;
    BEGIN SELECT agency_name INTO l_agn FROM agents WHERE agent_id=r.agent_id; EXCEPTION WHEN NO_DATA_FOUND THEN l_agn:=NULL; END;
    BEGIN SELECT full_name INTO l_apr FROM app_users WHERE user_id=r.approver_id; EXCEPTION WHEN NO_DATA_FOUND THEN l_apr:=NULL; END;
    BEGIN SELECT name_he,name_en INTO l_wohe,l_woen FROM wet_operators WHERE operator_id=r.wet_operator_id; EXCEPTION WHEN NO_DATA_FOUND THEN l_wohe:=NULL; l_woen:=NULL; END;
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE);
      APEX_JSON.open_object('booking');
        APEX_JSON.write('id',r.booking_id); APEX_JSON.write('seq',r.booking_id); APEX_JSON.write('status',r.status);
        APEX_JSON.write('dept_id',r.dept_id); APEX_JSON.write('dept_he',l_dhe); APEX_JSON.write('dept_en',l_den);
        APEX_JSON.write('initiator_id',r.initiator_id); APEX_JSON.write('initiator',l_ini);
        APEX_JSON.write('agent_id',r.agent_id); APEX_JSON.write('agent',l_agn);
        APEX_JSON.write('approver_id',r.approver_id); APEX_JSON.write('approver',l_apr);
        APEX_JSON.write('departure_date',TO_CHAR(r.departure_date,'YYYY-MM-DD'));
        APEX_JSON.write('open_date',TO_CHAR(r.open_date,'YYYY-MM-DD'));
        APEX_JSON.write('ticketing_date',TO_CHAR(r.ticketing_date,'YYYY-MM-DD'));
        APEX_JSON.write('price',r.price); APEX_JSON.write('currency',r.currency_code);
        APEX_JSON.write('pnr',r.pnr); APEX_JSON.write('unique_ref',r.unique_booking_ref);
        APEX_JSON.write('quote_notes',r.quote_notes); APEX_JSON.write('trip_details',r.trip_details);
        APEX_JSON.write('rejection_reason',r.rejection_reason); APEX_JSON.write('cancel_reason',r.cancel_reason);
        APEX_JSON.write('dept_code',l_dcode);
        APEX_JSON.write('pax',r.pax_count); APEX_JSON.write('pref_time',r.pref_time);
        APEX_JSON.write('origin',r.origin_iata); APEX_JSON.write('dest',r.dest_iata);
        APEX_JSON.write('wet_op_id',r.wet_operator_id);
        APEX_JSON.write('wet_op_he',l_wohe); APEX_JSON.write('wet_op_en',NVL(l_woen,l_wohe));
        APEX_JSON.write('low_cost',r.low_cost); APEX_JSON.write('urgent',r.urgent);
        DECLARE l_isapr NUMBER; BEGIN
          SELECT COUNT(*) INTO l_isapr FROM dept_approvers WHERE dept_id=r.dept_id AND approver_user_id=l_uid;
          APEX_JSON.write('can_approve',
            CASE WHEN has_role(l_uid,'ADMIN')='Y' OR NVL(r.approver_id,-1)=l_uid OR l_isapr>0 THEN 'Y' ELSE 'N' END);
        END;
      APEX_JSON.close_object;
      APEX_JSON.open_array('files');
        FOR f IN (SELECT file_id,file_kind,filename,mime_type FROM booking_files WHERE booking_id=p_id ORDER BY file_id) LOOP
          APEX_JSON.open_object; APEX_JSON.write('id',f.file_id); APEX_JSON.write('kind',f.file_kind);
          APEX_JSON.write('filename',f.filename); APEX_JSON.write('mime',f.mime_type); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
      APEX_JSON.open_array('log');
        FOR lg IN (SELECT l.from_status fs,l.to_status ts,u.full_name nm,TO_CHAR(l.action_at,'YYYY-MM-DD HH24:MI') atx,l.note nt
                   FROM booking_status_log l JOIN app_users u ON u.user_id=l.action_by
                   WHERE l.booking_id=p_id ORDER BY l.action_at DESC) LOOP
          APEX_JSON.open_object; APEX_JSON.write('from',lg.fs); APEX_JSON.write('to',lg.ts);
          APEX_JSON.write('by',lg.nm); APEX_JSON.write('at',lg.atx); APEX_JSON.write('note',lg.nt); APEX_JSON.close_object;
        END LOOP;
      APEX_JSON.close_array;
    APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END get_booking;

  -- התראה לכל הסוכנים הפעילים (מודל "בריכה" — כל סוכן יכול להגיב) — פעמון + מייל
  PROCEDURE notify_agents (p_id NUMBER) IS
  BEGIN
    FOR a IN (SELECT ag.agent_id, u.user_id, u.email, u.pref_lang, NVL(u.notify_email,'Y') notify
                FROM agents ag JOIN app_users u ON u.user_id = ag.user_id
               WHERE ag.is_active='Y' AND u.is_active='Y') LOOP
      INSERT INTO notifications (user_id, booking_id, notif_type, message)
      VALUES (a.user_id, p_id, 'AWAITING_QUOTE',
              CASE WHEN a.pref_lang='EN' THEN 'New quote request #'||p_id
                   ELSE 'בקשה חדשה להצעת מחיר #'||p_id END);
      IF a.email IS NOT NULL AND a.notify = 'Y' THEN
        BEGIN
          BEGIN APEX_UTIL.SET_SECURITY_GROUP_ID(APEX_UTIL.FIND_SECURITY_GROUP_ID('ARKIA')); EXCEPTION WHEN OTHERS THEN NULL; END;
          APEX_MAIL.SEND(p_to => a.email, p_from => booking_pkg.g_mail_from,
            p_subj => CASE WHEN a.pref_lang='EN' THEN 'Arkia — new quote request #'||p_id ELSE 'ארקיע — בקשה חדשה להצעת מחיר #'||p_id END,
            p_body => TO_CLOB((CASE WHEN a.pref_lang='EN' THEN 'A new booking is awaiting your quote. Sign in to respond.' ELSE 'התקבלה בקשה חדשה הממתינה להצעת מחיר. היכנסו למערכת כדי להגיב.' END)
                      || CHR(10) || booking_pkg.g_app_url || '#b=' || p_id),
            p_body_html => booking_pkg.booking_email_html(p_id, a.pref_lang));
        EXCEPTION WHEN OTHERS THEN NULL; END;
      END IF;
    END LOOP;
    BEGIN APEX_MAIL.PUSH_QUEUE; EXCEPTION WHEN OTHERS THEN NULL; END;
  END notify_agents;

  -- מייל לכל מאשרי המחלקה עם כפתור "אשר את ההצעה" (טוקן חד-פעמי לכל מאשר) — נשלח כשהוגשה הצעת מחיר
  PROCEDURE notify_approver_quote (p_id NUMBER) IS
    l_dept NUMBER; l_pinned NUMBER; l_any BOOLEAN := FALSE;
    l_token VARCHAR2(70); l_mail_id NUMBER; l_url VARCHAR2(400);
  BEGIN
    SELECT dept_id, approver_id INTO l_dept, l_pinned FROM bookings WHERE booking_id = p_id;
    -- נמעני האישור: כל המאשרים המוגדרים של המחלקה + המאשר המשויך (אם קיים), ללא כפילויות
    FOR a IN (
        SELECT u.user_id, u.email, u.pref_lang, NVL(u.notify_email,'Y') notify
          FROM app_users u
         WHERE u.user_id IN (
                 SELECT approver_user_id FROM dept_approvers WHERE dept_id = l_dept
                 UNION
                 SELECT l_pinned FROM dual WHERE l_pinned IS NOT NULL)
    ) LOOP
      l_any := TRUE;
      l_token := RAWTOHEX(SYS_GUID()) || RAWTOHEX(SYS_GUID());
      INSERT INTO booking_action_tokens (token, booking_id, action, user_id, expires_at)
        VALUES (l_token, p_id, 'approve', a.user_id, SYSTIMESTAMP + INTERVAL '7' DAY);
      INSERT INTO notifications (user_id, booking_id, notif_type, message)
        VALUES (a.user_id, p_id, 'QUOTE_RECEIVED',
          CASE WHEN a.pref_lang='EN' THEN 'A quote was submitted for booking #'||p_id||' — approval required'
               ELSE 'התקבלה הצעת מחיר להזמנה #'||p_id||' — נדרש אישור' END);
      IF a.email IS NOT NULL AND a.notify = 'Y' THEN
        l_url := REPLACE(booking_pkg.g_app_url, '/app', '') || '/act?t=' || l_token;
        BEGIN
          BEGIN APEX_UTIL.SET_SECURITY_GROUP_ID(APEX_UTIL.FIND_SECURITY_GROUP_ID('ARKIA')); EXCEPTION WHEN OTHERS THEN NULL; END;
          l_mail_id := APEX_MAIL.SEND(p_to => a.email, p_from => booking_pkg.g_mail_from,
            p_subj => CASE WHEN a.pref_lang='EN' THEN 'Arkia — approval required, booking #'||p_id ELSE 'ארקיע — נדרש אישור, הזמנה #'||p_id END,
            p_body => TO_CLOB((CASE WHEN a.pref_lang='EN' THEN 'A quote was submitted and requires your approval.' ELSE 'התקבלה הצעת מחיר הממתינה לאישורך.' END)
                      || CHR(10) || 'Approve: ' || l_url || CHR(10) || booking_pkg.g_app_url || '#b=' || p_id),
            p_body_html => booking_pkg.booking_email_html(p_id, a.pref_lang, l_url));
          FOR f IN (SELECT filename, mime_type, file_blob FROM booking_files WHERE booking_id = p_id) LOOP
            BEGIN APEX_MAIL.ADD_ATTACHMENT(p_mail_id => l_mail_id, p_attachment => f.file_blob,
              p_filename => f.filename, p_mime_type => NVL(f.mime_type,'application/octet-stream')); EXCEPTION WHEN OTHERS THEN NULL; END;
          END LOOP;
        EXCEPTION WHEN OTHERS THEN NULL; END;
      END IF;
    END LOOP;
    COMMIT;
    IF l_any THEN BEGIN APEX_MAIL.PUSH_QUEUE; EXCEPTION WHEN OTHERS THEN NULL; END; END IF;
  EXCEPTION WHEN OTHERS THEN NULL;   -- לא מפיל את הגשת ההצעה
  END notify_approver_quote;

  -- אישור/פעולה מתוך המייל (טוקן חד-פעמי). autonomous — מבצע DML ומחזיר עמוד HTML.
  FUNCTION act_token (p_t VARCHAR2) RETURN BLOB IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    l_bid NUMBER; l_uid NUMBER; l_action VARCHAR2(20); l_used CHAR(1);
    FUNCTION page (p_title VARCHAR2, p_msg VARCHAR2, p_bid NUMBER) RETURN BLOB IS
      l VARCHAR2(4000);
    BEGIN
      l := '<!doctype html><html dir="rtl" lang="he"><head><meta charset="utf-8">'||
           '<meta name="viewport" content="width=device-width,initial-scale=1"><title>'||p_title||'</title></head>'||
           '<body style="font-family:Heebo,Arial,sans-serif;background:#f2f5f9;margin:0;padding:24px">'||
           '<div style="max-width:460px;margin:40px auto;background:#fff;border-radius:14px;border:1px solid #e2e8f0;overflow:hidden">'||
           '<div style="background:#123a86;padding:16px;text-align:center">'||
           '<img src="'||booking_pkg.g_assets_url||'arkia" height="26" style="background:#fff;border-radius:6px;padding:3px 7px;vertical-align:middle">'||
           '<span style="color:#fff;margin:0 10px">&#10005;</span>'||
           '<img src="'||booking_pkg.g_assets_url||'teltos" height="26" style="background:#fff;border-radius:6px;padding:3px 7px;vertical-align:middle"></div>'||
           '<div style="padding:22px;text-align:center">'||
           '<h2 style="color:#123a86;margin:0 0 8px">'||p_title||'</h2>'||
           '<p style="color:#5b6b7f">'||p_msg||'</p>'||
           CASE WHEN p_bid IS NOT NULL THEN '<a href="'||booking_pkg.g_app_url||'#b='||p_bid||'" style="display:inline-block;margin-top:10px;background:#0e7a4e;color:#fff;text-decoration:none;padding:11px 22px;border-radius:9px;font-weight:700">צפייה בהזמנה</a>' ELSE '' END||
           '</div></div></body></html>';
      RETURN TO_BLOB(UTL_I18N.STRING_TO_RAW(l, 'AL32UTF8'));
    END page;
  BEGIN
    BEGIN
      SELECT booking_id, user_id, action, used INTO l_bid, l_uid, l_action, l_used
        FROM booking_action_tokens WHERE token = p_t AND expires_at > SYSTIMESTAMP;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      COMMIT; RETURN page('קישור לא תקין', 'הקישור אינו תקף או שפג תוקפו.', NULL);
    END;
    IF l_used = 'Y' THEN
      COMMIT; RETURN page('כבר טופל', 'הפעולה כבר בוצעה עבור הזמנה זו.', l_bid);
    END IF;
    IF l_action = 'approve' THEN
      booking_pkg.approve(l_bid, l_uid, 'אושר מתוך המייל');
    END IF;
    UPDATE booking_action_tokens SET used = 'Y' WHERE token = p_t;
    COMMIT;
    RETURN page('ההצעה אושרה ✓', 'ההזמנה אושרה בהצלחה. הסוכן יכול להמשיך לכרטוס.', l_bid);
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK; RETURN page('שגיאה', 'אירעה שגיאה בעיבוד הבקשה.', NULL);
  END act_token;

  FUNCTION create_booking (p_token VARCHAR2, p_departure VARCHAR2, p_notes VARCHAR2,
                           p_pax NUMBER, p_pref_time VARCHAR2, p_wet_op NUMBER,
                           p_origin VARCHAR2, p_dest VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token); l_dept NUMBER; l_id NUMBER;
  BEGIN
    SELECT dept_id INTO l_dept FROM app_users WHERE user_id = l_uid;
    -- מודל בריכה: אין סוכן ספציפי בייזום — ההזמנה נפתחת לכל הסוכנים.
    -- אין עדיין מחיר (נקבע ע"י הסוכן שיגיש הצעה). מטבע ברירת מחדל בלבד.
    INSERT INTO bookings (dept_id, initiator_id, agent_id, approver_id, status, open_date,
                          departure_date, currency_code, quote_notes,
                          pax_count, pref_time, wet_operator_id, origin_iata, dest_iata)
    VALUES (l_dept, l_uid, NULL, booking_pkg.derive_approver(l_dept), 'AWAITING_QUOTE', TRUNC(SYSDATE),
            TO_DATE(p_departure,'YYYY-MM-DD'), 'USD', p_notes,
            NVL(p_pax,1), p_pref_time, p_wet_op, UPPER(p_origin), UPPER(p_dest))
    RETURNING booking_id INTO l_id;
    INSERT INTO booking_status_log (booking_id, from_status, to_status, action_by, note)
    VALUES (l_id, NULL, 'AWAITING_QUOTE', l_uid, 'נפתחה לכל הסוכנים');
    notify_agents(l_id);
    COMMIT;
    RETURN '{"ok":true,"id":'||l_id||'}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END create_booking;

  -- עריכת פרטי הזמנה (יוזם / מאשר / אדמין) — מותרת רק עד לשלב הכרטוס
  FUNCTION edit_booking (p_token VARCHAR2, p_id NUMBER, p_departure VARCHAR2, p_agent_id NUMBER,
                         p_notes VARCHAR2, p_pax NUMBER, p_pref_time VARCHAR2, p_wet_op NUMBER,
                         p_origin VARCHAR2, p_dest VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token);
    l_status VARCHAR2(30); l_dept NUMBER; l_ini NUMBER; l_apr NUMBER; l_is_dept_apr NUMBER; l_ok BOOLEAN;
  BEGIN
    SELECT status, dept_id, initiator_id, approver_id INTO l_status, l_dept, l_ini, l_apr
      FROM bookings WHERE booking_id = p_id;
    -- לא ניתן לערוך לאחר כרטוס / ביטול / דחייה
    IF l_status IN ('TICKETED','CANCELLED','REJECTED') THEN RETURN err('booking_locked'); END IF;
    SELECT COUNT(*) INTO l_is_dept_apr FROM dept_approvers WHERE dept_id=l_dept AND approver_user_id=l_uid;
    l_ok := (l_ini = l_uid)
            OR (has_role(l_uid,'ADMIN')='Y')
            OR (has_role(l_uid,'APPROVER')='Y' AND (l_apr = l_uid OR l_is_dept_apr > 0));
    IF NOT l_ok THEN RETURN err('forbidden'); END IF;
    UPDATE bookings
       SET departure_date  = NVL(TO_DATE(p_departure,'YYYY-MM-DD'), departure_date),
           agent_id        = NVL(p_agent_id, agent_id),
           quote_notes     = NVL(p_notes, quote_notes),
           pax_count       = NVL(p_pax, pax_count),
           pref_time       = p_pref_time,
           wet_operator_id = p_wet_op,
           origin_iata     = UPPER(p_origin),
           dest_iata       = UPPER(p_dest),
           updated_at      = SYSTIMESTAMP
     WHERE booking_id = p_id;
    -- שורת אודיט (מאותו סטטוס אל עצמו) — כדי שיירשם "עודכן לאחרונה ע"י"
    INSERT INTO booking_status_log (booking_id, from_status, to_status, action_by, note)
    VALUES (p_id, l_status, l_status, l_uid, 'עריכת פרטי הזמנה');
    COMMIT;
    RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END edit_booking;

  FUNCTION do_action (p_token VARCHAR2, p_id NUMBER, p_action VARCHAR2,
                      p_price NUMBER, p_currency VARCHAR2, p_trip CLOB, p_notes VARCHAR2,
                      p_pnr VARCHAR2, p_ref VARCHAR2, p_tdate VARCHAR2, p_reason VARCHAR2,
                      p_low_cost VARCHAR2 DEFAULT NULL) RETURN CLOB IS
    l_uid NUMBER := uid(p_token);
  BEGIN
    CASE p_action
      WHEN 'submit_quote'   THEN
        -- מודל בריכה: הסוכן שמגיש את ההצעה משויך להזמנה (אם עדיין לא משויכת)
        UPDATE bookings SET agent_id = (SELECT MAX(agent_id) FROM agents WHERE user_id = l_uid)
         WHERE booking_id = p_id AND agent_id IS NULL;
        UPDATE bookings SET low_cost = NVL(p_low_cost,'N') WHERE booking_id = p_id;
        booking_pkg.submit_quote(p_id, p_price, p_currency, p_trip, p_notes, l_uid);
        notify_approver_quote(p_id);   -- מייל למאשר עם כפתור אישור ישיר
      WHEN 'approve'        THEN
        IF NOT is_booking_approver(l_uid, p_id) THEN RETURN err('forbidden'); END IF;
        booking_pkg.approve(p_id, l_uid, p_notes);
      WHEN 'reject'         THEN
        IF NOT is_booking_approver(l_uid, p_id) THEN RETURN err('forbidden'); END IF;
        booking_pkg.reject(p_id, l_uid, p_reason);
      WHEN 'ticket'         THEN booking_pkg.ticket(p_id, p_pnr, p_ref, TO_DATE(p_tdate,'YYYY-MM-DD'), l_uid);
      WHEN 'request_cancel' THEN
        -- אישור ביטול ע"י הסוכן נדרש רק לאחר כרטוס. לפני כרטוס — ביטול מיידי.
        DECLARE l_st VARCHAR2(30); BEGIN
          SELECT status INTO l_st FROM bookings WHERE booking_id = p_id;
          IF l_st = 'TICKETED' THEN
            booking_pkg.request_cancel(p_id, l_uid, p_reason);          -- דו-שלבי
          ELSE
            UPDATE bookings SET cancel_reason = p_reason, cancel_requested_by = l_uid,
                   cancel_requested_at = SYSTIMESTAMP WHERE booking_id = p_id;
            booking_pkg.change_status(p_id, 'CANCELLED', l_uid, p_reason);  -- מיידי
          END IF;
        END;
      WHEN 'confirm_cancel' THEN booking_pkg.confirm_cancel(p_id, l_uid, p_notes);
      ELSE RETURN err('unknown_action');
    END CASE;
    COMMIT;
    RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END do_action;

  -- הצעת מחיר דחופה — הסוכן יוזם הצעה ללא בקשה. נפתחת ישר ב-QUOTE_RECEIVED,
  -- מסומנת urgent, ומופנית למאשר של המחלקה שנבחרה.
  FUNCTION agent_create_quote (p_token VARCHAR2, p_dept_id NUMBER, p_departure VARCHAR2, p_pax NUMBER,
                          p_pref_time VARCHAR2, p_origin VARCHAR2, p_dest VARCHAR2, p_price NUMBER,
                          p_currency VARCHAR2, p_trip CLOB, p_notes VARCHAR2, p_low_cost VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token); l_agent NUMBER; l_id NUMBER;
  BEGIN
    IF has_role(l_uid,'AGENT') <> 'Y' THEN RETURN err('forbidden'); END IF;
    SELECT MAX(agent_id) INTO l_agent FROM agents WHERE user_id = l_uid;
    INSERT INTO bookings (dept_id, initiator_id, agent_id, approver_id, status, open_date, departure_date,
                          price, currency_code, quote_notes, trip_details, pax_count, pref_time,
                          origin_iata, dest_iata, low_cost, urgent)
    VALUES (p_dept_id, l_uid, l_agent, booking_pkg.derive_approver(p_dept_id), 'QUOTE_RECEIVED', TRUNC(SYSDATE),
            TO_DATE(p_departure,'YYYY-MM-DD'), p_price, NVL(p_currency,'USD'), p_notes, p_trip, NVL(p_pax,1),
            p_pref_time, UPPER(p_origin), UPPER(p_dest), NVL(p_low_cost,'N'), 'Y')
    RETURNING booking_id INTO l_id;
    INSERT INTO booking_status_log (booking_id, from_status, to_status, action_by, note)
    VALUES (l_id, NULL, 'QUOTE_RECEIVED', l_uid, 'הצעת מחיר דחופה (יזומה ע"י הסוכן)');
    notify_approver_quote(l_id);
    COMMIT;
    RETURN '{"ok":true,"id":'||l_id||'}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END agent_create_quote;

  FUNCTION add_file (p_token VARCHAR2, p_booking_id NUMBER, p_kind VARCHAR2,
                     p_filename VARCHAR2, p_mime VARCHAR2, p_data CLOB) RETURN CLOB IS
    l_uid NUMBER := uid(p_token); l_blob BLOB;
  BEGIN
    l_blob := APEX_WEB_SERVICE.CLOBBASE642BLOB(p_data);
    INSERT INTO booking_files (booking_id, file_kind, filename, mime_type, file_blob, uploaded_by)
    VALUES (p_booking_id, p_kind, p_filename, p_mime, l_blob, l_uid);
    COMMIT;
    RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END add_file;

  PROCEDURE get_file (p_id NUMBER, o_blob OUT BLOB, o_mime OUT VARCHAR2, o_name OUT VARCHAR2) IS
  BEGIN
    SELECT file_blob, NVL(mime_type,'application/octet-stream'), filename
      INTO o_blob, o_mime, o_name FROM booking_files WHERE file_id = p_id;
  END get_file;

  FUNCTION notifications (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token);
  BEGIN
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE); APEX_JSON.open_array('notifications');
    FOR n IN (SELECT notif_id,booking_id,message,is_read,TO_CHAR(created_at,'YYYY-MM-DD HH24:MI') atx
              FROM notifications WHERE user_id = l_uid ORDER BY created_at DESC) LOOP
      APEX_JSON.open_object; APEX_JSON.write('id',n.notif_id); APEX_JSON.write('booking_id',n.booking_id);
      APEX_JSON.write('message',n.message); APEX_JSON.write('is_read',n.is_read); APEX_JSON.write('at',n.atx); APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array; APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END notifications;

  FUNCTION mark_read (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token);
  BEGIN
    UPDATE notifications SET is_read='Y' WHERE user_id = l_uid AND is_read='N';
    COMMIT;
    RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN RETURN err(SQLERRM);
  END mark_read;

  --------------------------------------------------------------------------------
  -- ניהול (ADMIN בלבד)
  --------------------------------------------------------------------------------
  FUNCTION admin_guard (p_token VARCHAR2) RETURN NUMBER IS
    l_uid NUMBER := uid(p_token);
  BEGIN
    IF has_role(l_uid,'ADMIN') <> 'Y' THEN RAISE_APPLICATION_ERROR(-20403,'forbidden'); END IF;
    RETURN l_uid;
  END admin_guard;

  FUNCTION admin_users (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE); APEX_JSON.open_array('users');
    FOR u IN (
      SELECT u.user_id, u.username, u.full_name, u.email, u.dept_id, d.name_he dh,
             (SELECT LISTAGG(role_code, ',') WITHIN GROUP (ORDER BY role_code)
                FROM user_roles r WHERE r.user_id = u.user_id) roles
      FROM app_users u LEFT JOIN departments d ON d.dept_id = u.dept_id
      ORDER BY u.user_id
    ) LOOP
      APEX_JSON.open_object;
        APEX_JSON.write('id',u.user_id); APEX_JSON.write('username',u.username);
        APEX_JSON.write('full_name',u.full_name); APEX_JSON.write('email',u.email);
        APEX_JSON.write('dept_id',u.dept_id); APEX_JSON.write('dept',u.dh); APEX_JSON.write('roles',u.roles);
      APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array; APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END admin_users;

  FUNCTION admin_create_dept (p_token VARCHAR2, p_code VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    INSERT INTO departments (dept_code, name_he, name_en)
    VALUES (p_code, p_name_he, NVL(p_name_en, p_name_he));
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_create_dept;

  -- עדכון שם/קוד מחלקה קיימת
  FUNCTION admin_update_dept (p_token VARCHAR2, p_dept_id NUMBER, p_code VARCHAR2,
                              p_name_he VARCHAR2, p_name_en VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    IF p_name_he IS NULL THEN RETURN err('no_name'); END IF;
    UPDATE departments
       SET name_he   = p_name_he,
           name_en   = NVL(p_name_en, p_name_he),
           dept_code = NVL(p_code, dept_code)
     WHERE dept_id = p_dept_id;
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_update_dept;

  FUNCTION admin_create_user (p_token VARCHAR2, p_username VARCHAR2, p_full VARCHAR2, p_email VARCHAR2,
                              p_dept_id NUMBER, p_role VARCHAR2, p_password VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
    l_new NUMBER;
  BEGIN
    INSERT INTO app_users (username, full_name, email, dept_id, pref_lang)
    VALUES (LOWER(p_username), p_full, p_email, p_dept_id, 'HE') RETURNING user_id INTO l_new;
    INSERT INTO user_roles (user_id, role_code) VALUES (l_new, p_role);
    IF p_role = 'AGENT' THEN
      INSERT INTO agents (user_id, agency_name) VALUES (l_new, p_full);
    END IF;
    IF p_role = 'APPROVER' AND p_dept_id IS NOT NULL THEN
      INSERT INTO dept_approvers (dept_id, approver_user_id) VALUES (p_dept_id, l_new);
    END IF;
    booking_pkg.set_password(LOWER(p_username), NVL(p_password, 'Arkia2026!'));
    COMMIT; RETURN '{"ok":true,"id":'||l_new||'}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_create_user;

  FUNCTION admin_update_user (p_token VARCHAR2, p_user_id NUMBER, p_full VARCHAR2, p_email VARCHAR2,
                              p_dept_id NUMBER, p_is_active VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    UPDATE app_users
       SET full_name = NVL(p_full, full_name),
           email     = NVL(p_email, email),
           dept_id   = p_dept_id,
           is_active = NVL(p_is_active, is_active)
     WHERE user_id = p_user_id;
    IF SQL%ROWCOUNT = 0 THEN RETURN err('user_not_found'); END IF;
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_update_user;

  FUNCTION admin_setpw (p_token VARCHAR2, p_username VARCHAR2, p_password VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    booking_pkg.set_password(LOWER(p_username), p_password);
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_setpw;

  -- איפוס סיסמה: מייצר סיסמה זמנית אקראית, קובע אותה, ו**שולח אותה במייל** למשתמש.
  -- (סיסמאות נשמרות כ-hash חד-כיווני ולכן לא ניתן להציג סיסמה קיימת — רק לאפס.)
  -- אם שליחת המייל נכשלה / אין למשתמש מייל — הסיסמה הזמנית מוחזרת להצגה חד-פעמית.
  FUNCTION admin_reset_pw (p_token VARCHAR2, p_user_id NUMBER) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
    l_username app_users.username%TYPE;
    l_email    app_users.email%TYPE;
    l_lang     app_users.pref_lang%TYPE;
    l_temp     VARCHAR2(20);
    l_subj     VARCHAR2(200);
    l_body     VARCHAR2(1000);
  BEGIN
    SELECT username, email, pref_lang INTO l_username, l_email, l_lang
      FROM app_users WHERE user_id = p_user_id;
    -- סיסמה זמנית: 2 אותיות + 4 תווים + 4 ספרות (קריאה, חד-פעמית)
    l_temp := 'Ar' || SUBSTR(RAWTOHEX(SYS_GUID()),1,4) || TRUNC(DBMS_RANDOM.VALUE(1000,9999));
    booking_pkg.set_password(l_username, l_temp);
    COMMIT;

    -- שליחת המייל (best-effort). g_mail_from = ה-Approved Sender המאושר.
    IF l_email IS NOT NULL THEN
      IF l_lang = 'EN' THEN
        l_subj := 'Arkia Bookings — password reset';
        l_body := 'Your password was reset by an administrator.' || CHR(10) ||
                  'Username: ' || l_username || CHR(10) ||
                  'Temporary password: ' || l_temp || CHR(10) ||
                  'Please sign in and change it.';
      ELSE
        l_subj := 'מערכת הזמנות ארקיע — איפוס סיסמה';
        l_body := 'הסיסמה שלך אופסה על ידי מנהל המערכת.' || CHR(10) ||
                  'שם משתמש: ' || l_username || CHR(10) ||
                  'סיסמה זמנית: ' || l_temp || CHR(10) ||
                  'יש להתחבר ולהחליף אותה.';
      END IF;
      BEGIN
        BEGIN APEX_UTIL.SET_SECURITY_GROUP_ID(APEX_UTIL.FIND_SECURITY_GROUP_ID('ARKIA')); EXCEPTION WHEN OTHERS THEN NULL; END;
        APEX_MAIL.SEND(p_to => l_email, p_from => booking_pkg.g_mail_from, p_subj => l_subj, p_body => l_body);
        BEGIN APEX_MAIL.PUSH_QUEUE; EXCEPTION WHEN OTHERS THEN NULL; END;
        RETURN '{"ok":true,"emailed":true,"username":"'||l_username||'","email":"'||l_email||'"}';
      EXCEPTION WHEN OTHERS THEN
        -- מייל נכשל — נחזיר את הסיסמה הזמנית למסירה ידנית
        RETURN '{"ok":true,"emailed":false,"username":"'||l_username||'","temp_password":"'||l_temp||'"}';
      END;
    END IF;
    -- אין מייל למשתמש
    RETURN '{"ok":true,"emailed":false,"username":"'||l_username||'","temp_password":"'||l_temp||'"}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_reset_pw;

  FUNCTION admin_create_wetop (p_token VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    INSERT INTO wet_operators (name_he, name_en) VALUES (p_name_he, NVL(p_name_en, p_name_he));
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_create_wetop;

  -- מיפוי מחלקה → מאשר נוכחי
  FUNCTION admin_dept_approvers (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE); APEX_JSON.open_array('approvers');
    FOR r IN (SELECT da.dept_id, da.approver_user_id uid, u.full_name nm
                FROM dept_approvers da JOIN app_users u ON u.user_id = da.approver_user_id
                ORDER BY da.dept_id) LOOP
      APEX_JSON.open_object; APEX_JSON.write('dept_id', r.dept_id); APEX_JSON.write('user_id', r.uid);
      APEX_JSON.write('name', r.nm); APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array; APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END admin_dept_approvers;

  -- הוספת מאשר למחלקה (תומך בכמה מאשרים למחלקה). מקנה תפקיד APPROVER.
  FUNCTION admin_set_dept_approver (p_token VARCHAR2, p_dept_id NUMBER, p_user_id NUMBER) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token); n PLS_INTEGER;
  BEGIN
    IF p_user_id IS NULL THEN RETURN err('no_user'); END IF;
    SELECT COUNT(*) INTO n FROM dept_approvers WHERE dept_id = p_dept_id AND approver_user_id = p_user_id;
    IF n = 0 THEN INSERT INTO dept_approvers (dept_id, approver_user_id) VALUES (p_dept_id, p_user_id); END IF;
    SELECT COUNT(*) INTO n FROM user_roles WHERE user_id = p_user_id AND role_code = 'APPROVER';
    IF n = 0 THEN INSERT INTO user_roles (user_id, role_code) VALUES (p_user_id, 'APPROVER'); END IF;
    -- אם להזמנות פתוחות של המחלקה אין עדיין מאשר משויך — משייכים את המאשר הזה
    UPDATE bookings SET approver_id = p_user_id
      WHERE dept_id = p_dept_id AND approver_id IS NULL AND status NOT IN ('TICKETED','CANCELLED','REJECTED');
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_set_dept_approver;

  -- הסרת מאשר ממחלקה
  FUNCTION admin_del_dept_approver (p_token VARCHAR2, p_dept_id NUMBER, p_user_id NUMBER) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    DELETE FROM dept_approvers WHERE dept_id = p_dept_id AND approver_user_id = p_user_id;
    -- הזמנות פתוחות ששויכו למאשר שהוסר — מאפסים כדי שיחזרו לבריכת מאשרי המחלקה
    UPDATE bookings SET approver_id = NULL
      WHERE dept_id = p_dept_id AND approver_id = p_user_id AND status NOT IN ('TICKETED','CANCELLED','REJECTED');
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_del_dept_approver;

  -- מחיקת משתמש. חסום אם למשתמש יש הזמנות מקושרות (FK) — מחזיר שגיאה ברורה.
  FUNCTION admin_delete_user (p_token VARCHAR2, p_user_id NUMBER) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
    n PLS_INTEGER;
  BEGIN
    IF p_user_id = l_uid THEN RETURN err('cannot_delete_self'); END IF;
    SELECT COUNT(*) INTO n FROM bookings
      WHERE initiator_id = p_user_id OR approver_id = p_user_id
         OR cancel_requested_by = p_user_id
         OR agent_id IN (SELECT agent_id FROM agents WHERE user_id = p_user_id);
    IF n > 0 THEN RETURN err('user_has_bookings'); END IF;
    DELETE FROM dept_approvers WHERE approver_user_id = p_user_id;
    DELETE FROM agents         WHERE user_id = p_user_id;
    DELETE FROM user_roles     WHERE user_id = p_user_id;   -- FK cascade ממילא
    DELETE FROM app_users      WHERE user_id = p_user_id;
    IF SQL%ROWCOUNT = 0 THEN ROLLBACK; RETURN err('user_not_found'); END IF;
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_delete_user;

  -- לוג כניסות (100 האחרונות)
  FUNCTION admin_logins (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE); APEX_JSON.open_array('logins');
    FOR r IN (SELECT l.username, u.full_name,
                     TO_CHAR(l.login_at,'YYYY-MM-DD HH24:MI:SS') atx
                FROM login_log l LEFT JOIN app_users u ON u.user_id = l.user_id
               ORDER BY l.login_at DESC FETCH FIRST 100 ROWS ONLY) LOOP
      APEX_JSON.open_object; APEX_JSON.write('username', r.username);
      APEX_JSON.write('full_name', r.full_name); APEX_JSON.write('at', r.atx); APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array; APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END admin_logins;

  -- כל משתמש מדליק/מכבה התראות מייל לעצמו
  FUNCTION set_notify (p_token VARCHAR2, p_on VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := uid(p_token);
  BEGIN
    UPDATE app_users SET notify_email = CASE WHEN p_on = 'Y' THEN 'Y' ELSE 'N' END
     WHERE user_id = l_uid;
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END set_notify;

  -- רשימת כל שדות התעופה (כולל לא-פעילים) — לניהול ע"י אדמין
  FUNCTION admin_airports (p_token VARCHAR2) RETURN CLOB IS
    l_uid NUMBER := admin_guard(p_token);
  BEGIN
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object; APEX_JSON.write('ok', TRUE); APEX_JSON.open_array('airports');
    FOR a IN (SELECT iata,name_he,name_en,country,is_active FROM airports ORDER BY iata) LOOP
      APEX_JSON.open_object; APEX_JSON.write('iata',a.iata); APEX_JSON.write('name_he',a.name_he);
      APEX_JSON.write('name_en',a.name_en); APEX_JSON.write('country',a.country);
      APEX_JSON.write('is_active',a.is_active); APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array; APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END admin_airports;

  -- הוספה/עדכון שדה תעופה (MERGE לפי IATA) + הפעלה/השבתה
  FUNCTION admin_save_airport (p_token VARCHAR2, p_iata VARCHAR2, p_name_he VARCHAR2, p_name_en VARCHAR2,
                               p_country VARCHAR2, p_is_active VARCHAR2) RETURN CLOB IS
    l_uid  NUMBER := admin_guard(p_token);
    l_iata VARCHAR2(4) := UPPER(TRIM(p_iata));
  BEGIN
    IF l_iata IS NULL THEN RETURN err('iata_required'); END IF;
    MERGE INTO airports a USING (SELECT l_iata AS iata FROM dual) s ON (a.iata = s.iata)
    WHEN MATCHED THEN UPDATE SET
      name_he   = NVL(p_name_he, a.name_he),
      name_en   = NVL(p_name_en, a.name_en),
      country   = NVL(p_country, a.country),
      is_active = NVL(p_is_active, a.is_active)
    WHEN NOT MATCHED THEN INSERT (iata, name_he, name_en, city_he, city_en, country, is_active)
      VALUES (l_iata, p_name_he, NVL(p_name_en, p_name_he), p_name_he, NVL(p_name_en, p_name_he),
              p_country, NVL(p_is_active,'Y'));
    COMMIT; RETURN '{"ok":true}';
  EXCEPTION WHEN OTHERS THEN ROLLBACK; RETURN err(SQLERRM);
  END admin_save_airport;

  -- בקרת שימוש: נפח אחסון (GB, סכמת ARKIA) ומיילים שנשלחו החודש — מול מכסות ה-Free Tier.
  FUNCTION admin_usage (p_token VARCHAR2) RETURN CLOB IS
    l_uid   NUMBER := admin_guard(p_token);
    l_gb    NUMBER := 0;
    l_mails NUMBER := 0;
  BEGIN
    -- שאילתות דינמיות (EXECUTE IMMEDIATE) כדי שהחבילה תתקמפל גם אם View/עמודה חסרים בסביבה
    BEGIN EXECUTE IMMEDIATE 'SELECT ROUND(NVL(SUM(bytes),0)/1024/1024/1024,3) FROM user_segments' INTO l_gb;
    EXCEPTION WHEN OTHERS THEN l_gb := 0; END;
    -- שם עמודת התאריך ב-APEX_MAIL_LOG משתנה בין גרסאות; מנסים כמה מועמדים ואז נופלים לספירה כוללת
    BEGIN
      DECLARE l_col VARCHAR2(30);
      BEGIN
        SELECT column_name INTO l_col FROM all_tab_columns
         WHERE table_name = 'APEX_MAIL_LOG' AND column_name IN ('LOG_TIMESTAMP','SENT_ON','CREATED_ON','AGGREGATE_ON')
         AND ROWNUM = 1;
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM apex_mail_log WHERE '||l_col||' >= TRUNC(SYSDATE,''MM'')' INTO l_mails;
      EXCEPTION WHEN OTHERS THEN
        BEGIN EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM apex_mail_log' INTO l_mails;
        EXCEPTION WHEN OTHERS THEN l_mails := 0; END;
      END;
    END;
    APEX_JSON.initialize_clob_output;
    APEX_JSON.open_object;
      APEX_JSON.write('ok', TRUE);
      APEX_JSON.write('storage_gb', l_gb);
      APEX_JSON.write('storage_limit_gb', 250);
      APEX_JSON.write('emails_month', l_mails);
      APEX_JSON.write('emails_limit', 3000);
    APEX_JSON.close_object;
    RETURN APEX_JSON.get_clob_output;
  EXCEPTION WHEN OTHERS THEN APEX_JSON.free_output; RETURN err(SQLERRM);
  END admin_usage;

END api_pkg;
/

--------------------------------------------------------------------------------
-- הגדרת מודול ה-ORDS (REST)
-- הערה: ORDS מתיר handler מסוג PL/SQL רק ל-POST/PUT/DELETE (לא GET).
--       לכן כל קריאות הנתונים הן POST (פרמטרים ב-form body), ping=query, files=media.
--       שליחת form-urlencoded מהדפדפן נחשבת "simple request" → אין preflight/OPTIONS.
--------------------------------------------------------------------------------
BEGIN
  BEGIN ORDS.DELETE_MODULE(p_module_name => 'arkia.api'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_MODULE(
    p_module_name => 'arkia.api',
    p_base_path   => 'api/',
    p_status      => 'PUBLISHED',
    p_comments    => 'Arkia bookings REST API');

  -- ping (GET, query — בדיקת חיים בדפדפן)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'ping');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'ping', p_method=>'GET',
    p_source_type=>ORDS.source_type_query,
    p_source=>q'[SELECT 'ok' AS status, 'arkia-api' AS service FROM dual]');

  -- login (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'login');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'login', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.login(:username, :password)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- bootstrap (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'bootstrap');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'bootstrap', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.bootstrap(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- bookings (POST = list)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'bookings');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'bookings', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.list_bookings(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- bookings/create (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'bookings/create');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'bookings/create', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.create_booking(:token, :departure, :notes, :pax, :pref_time, :wet_op, :origin, :dest)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- agent/quote/create (POST) — הצעת מחיר דחופה יזומה ע"י הסוכן
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'agent/quote/create');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'agent/quote/create', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.agent_create_quote(:token, :dept_id, :departure, :pax, :pref_time, :origin, :dest, :price, :currency, :trip, :notes, :low_cost)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- bookings/edit (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'bookings/edit');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'bookings/edit', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.edit_booking(:token, :id, :departure, :agent_id, :notes, :pax, :pref_time, :wet_op, :origin, :dest)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- bookings/get (POST = detail)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'bookings/get');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'bookings/get', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.get_booking(:token, :id)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- bookings/action (POST = workflow)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'bookings/action');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'bookings/action', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.do_action(:token, :id, :action, :price, :currency, :trip, :notes, :pnr, :ref, :tdate, :reason, :low_cost)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- notifications (POST = list)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'notifications');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'notifications', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.notifications(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- notifications/read (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'notifications/read');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'notifications/read', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.mark_read(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- files/upload (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'files/upload');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'files/upload', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.add_file(:token, :booking_id, :kind, :filename, :mime, :data)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- files/:id (GET, media — הורדה/תצוגה של קובץ)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'files/:id');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'files/:id', p_method=>'GET',
    p_source_type=>ORDS.source_type_media,
    p_source=>q'[SELECT NVL(mime_type,'application/octet-stream') AS content_type, file_blob FROM booking_files WHERE file_id = :id]');

  -- act (GET, media — אישור/פעולה מתוך המייל דרך טוקן חד-פעמי; מחזיר עמוד HTML)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'act');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'act', p_method=>'GET',
    p_source_type=>ORDS.source_type_media,
    p_source=>q'[SELECT 'text/html; charset=utf-8' AS content_type, api_pkg.act_token(:t) AS content FROM dual]');

  -- admin/users (POST = list)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/users');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/users', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_users(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/dept/create (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/dept/create');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/dept/create', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_create_dept(:token, :code, :name_he, :name_en)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/dept/update (POST = עריכת שם/קוד מחלקה)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/dept/update');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/dept/update', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_update_dept(:token, :dept_id, :code, :name_he, :name_en)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/user/create (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/user/create');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/user/create', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_create_user(:token, :username, :full, :email, :dept_id, :role, :password)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/setpw (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/setpw');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/setpw', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_setpw(:token, :username, :password)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/user/update (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/user/update');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/user/update', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_update_user(:token, :user_id, :full, :email, :dept_id, :is_active)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/resetpw (POST) — מחזיר סיסמה זמנית פעם אחת
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/resetpw');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/resetpw', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_reset_pw(:token, :user_id)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/wetop/create (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/wetop/create');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/wetop/create', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_create_wetop(:token, :name_he, :name_en)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/airports (POST = list כולל לא-פעילים)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/airports');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/airports', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_airports(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/airport/save (POST = upsert + הפעלה/השבתה)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/airport/save');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/airport/save', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_save_airport(:token, :iata, :name_he, :name_en, :country, :is_active)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/user/delete (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/user/delete');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/user/delete', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_delete_user(:token, :user_id)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/logins (POST = login log)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/logins');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/logins', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_logins(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/usage (POST = בקרת שימוש: אחסון + מיילים)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/usage');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/usage', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_usage(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- notify/set (POST = הדלקת/כיבוי מייל למשתמש)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'notify/set');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'notify/set', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.set_notify(:token, :on)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/dept_approvers (POST = מיפוי מחלקה→מאשר)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/dept_approvers');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/dept_approvers', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_dept_approvers(:token)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/dept_approver/set (POST)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/dept_approver/set');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/dept_approver/set', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_set_dept_approver(:token, :dept_id, :user_id)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  -- admin/dept_approver/del (POST = הסרת מאשר ממחלקה)
  ORDS.DEFINE_TEMPLATE(p_module_name => 'arkia.api', p_pattern => 'admin/dept_approver/del');
  ORDS.DEFINE_HANDLER(p_module_name=>'arkia.api', p_pattern=>'admin/dept_approver/del', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql,
    p_source=>q'[BEGIN api_pkg.emit(api_pkg.admin_del_dept_approver(:token, :dept_id, :user_id)); EXCEPTION WHEN OTHERS THEN api_pkg.emit(api_pkg.err(SQLERRM)); END;]');

  COMMIT;
END;
/


--------------------------------------------------------------------------------
-- מיתוג: ודא שם הסוכן הנכון (טלטוס) בנתונים החיים — idempotent, רץ בכל פריסה
--------------------------------------------------------------------------------
BEGIN
  UPDATE app_users SET username='teltos', full_name='טלטוס - סוכן נסיעות' WHERE username='toustous';
  UPDATE app_users SET full_name='טלטוס - סוכן נסיעות' WHERE username='teltos';
  UPDATE agents SET agency_name='טלטוס - מנועי חיפוש טיסות' WHERE agency_name LIKE 'טוסטוס%' OR agency_name LIKE 'טלטוס%';
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------------------------------------
-- רה-קומפילציה של אובייקטים שנפסלו ע"י מיגרציית הסכמה.
-- ALTER TABLE bookings (הוספת עמודות) פוסל חבילות התלויות ב-bookings%ROWTYPE
-- (כגון booking_pkg). ללא רה-קומפילציה מפורשת, בדיקת ה-VALID ב-CI תיכשל.
--------------------------------------------------------------------------------
BEGIN
  FOR o IN (SELECT object_name FROM user_objects WHERE object_type='PACKAGE' AND status='INVALID') LOOP
    BEGIN EXECUTE IMMEDIATE 'ALTER PACKAGE "'||o.object_name||'" COMPILE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
  FOR o IN (SELECT object_name FROM user_objects WHERE object_type='PACKAGE BODY' AND status='INVALID') LOOP
    BEGIN EXECUTE IMMEDIATE 'ALTER PACKAGE "'||o.object_name||'" COMPILE BODY'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
END;
/

PROMPT ✔ install_api.sql — שכבת ה-REST הותקנה. בסיס: /ords/arkia/api/
